<!DOCTYPE html>
<html lang="ja">
	<head>
		<title>Shiori Server Status</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width,user-scalable=no,maximum-scale=1">
		<link type="text/css" rel="stylesheet" href="css/main.css">
	</head>
	<body>
		<main>
			<p>
				Generated by Shiori Server Status<br>
				Version 1.2.0 (2022-06-07)<br>
				<a href="https://github.com/arkwnet/shiori-server-status" target="blank">
					https://github.com/arkwnet/shiori-server-status
				</a>
			</p>
			<p>
				Last updated on :<br>
				<?php
					echo file_get_contents("status_date.txt");
				?>
			</p>
			<p>
				<?php
					$vmstat = file_get_contents("status_vmstat.txt");
					$vmstat = explode("\n", $vmstat);
					$vmstat_count = count($vmstat);
					for ($i = 0; $i < $vmstat_count; $i++) {
						echo($vmstat[$i]);
						if ($i <= $vmstat_count - 2) {
							echo("<br>");
						}
					}
				?>
			</p>
			<p>
				<?php
					$df = file_get_contents("status_df.txt");
					$df = explode("\n", $df);
					$df_count = count($df);
					for ($i = 0; $i < $df_count; $i++) {
						echo($df[$i]);
						if ($i <= $df_count - 2) {
							echo("<br>");
						}
					}
				?>
			</p>
		</main>
	</body>
</html>
